apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: NodePort
  selector:
    app: healthcare-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005